# Note: You must pass environment variable SERVERNAME at the time of running 
# docker-compose up. 
#  `docker-compose up -d -e SERVERNAME=something.typeset.io`
version: "3"
services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs
    image: mysql:5.6
    volumes:
      - db-data:/var/lib/mysql/data
    networks:
      - backend

  ojs:
    environment:
      - OJS_VERSION=ojs-stable-3_0_2
      - OJS_DB_HOST=mysql
      - OJS_DB_USER=ojs
      - OJS_DB_PASSWORD=ojs
    build: .
    ports:
      - "8090:80"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

volumes:
  db-data: